stages:
  - build
  - release
  - sync

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  DOCKERFILE_PATH: ./Dockerfile

.docker_setup: &docker_setup
  image: docker:27-cli
  services: 
    - docker:27-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build-image-stg:
  <<: *docker_setup
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  script:
    - docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA  -t $IMAGE_NAME:dev .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:dev

build-image-prod:
  <<: *docker_setup
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - echo "Building Production Release $CI_COMMIT_TAG..."
    - docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME:$CI_COMMIT_TAG -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $IMAGE_NAME:latest

build-assets:
  stage: build
  image: node:24.14.0-alpine
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - corepack enable && corepack prepare pnpm@latest --activate
  script:
    - pnpm install --frozen-lockfile
    - echo "window.APP_CONFIG = { VAR_1:'VALUE_1' };" > public/env-config.js
    - pnpm run build
  artifacts:
    name: "build-release-$CI_COMMIT_TAG"
    paths:
      - dist/
    expire_in: 10 yrs

gitlab-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  needs:
    - job: build-assets
      artifacts: true
  script:
    - echo "Creating GitLab Release for $CI_COMMIT_TAG"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Docker image'
          url: 'https://$IMAGE_NAME:$CI_COMMIT_TAG'
        - name: 'Build Artifacts (dist.zip)'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/download?job=build-assets'

push_to_github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add git
  script:
    - git remote add github https://th-thong:${GITHUB_TOKEN}@${GITHUB_REPO_URL}
    - git checkout ${CI_COMMIT_REF_NAME}
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        git push github HEAD:refs/heads/${CI_DEFAULT_BRANCH} --force
        git push github "refs/tags/${CI_COMMIT_TAG}" --force
      else
        git push github HEAD:refs/heads/${CI_COMMIT_REF_NAME} --force
      fi